#!/bin/bash
# messaging_app/kubctl-0x01

kubectl scale deployment django-messaging-app --replicas=3

sleep 10

kubectl get pods -l app=django-messaging-app

wrk -t2 -c10 -d10s http://$(minikube service django-messaging-service --url)

kubectl top pods
