#!/bin/bash
# messaging_app/kubctl-0x03

kubectl apply -f messaging_app/blue_deployment.yaml

kubectl rollout status deployment/django-messaging-blue

echo "Checking for downtime..."
for i in {1..20}; do
  curl -s http://$(minikube service django-messaging-service --url) || echo "Request failed"
  sleep 1
done

# Verify pods are running
kubectl get pods -l app=django-messaging,version=blue
